"""
FinOps Monte Carlo Framework - Ranking Stability Analysis

Loads Monte Carlo sample matrices generated by
01_sensitivity_analysis_framework.py and runs Scenarios A, B, and C
under observed Gaussian, independent, and Student's t-copula conditions.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

from scenarios.scenario_a import ScenarioA
from scenarios.scenario_b import ScenarioB
from scenarios.scenario_c import ScenarioC


# ============================================================================
# CONFIGURATION AND FILE PATHS
# ============================================================================

CONFIG_PATH = Path("config/params_config.json")
SAMPLES_DIR = Path("results")
SAMPLES_FILE = SAMPLES_DIR / "samples_by_correlation.json"
RANKING_OUTPUT = SAMPLES_DIR / "ranking_by_correlation.json"
RANKING_SUMMARY = SAMPLES_DIR / "ranking_stability_summary.txt"

VARIABLE_ORDER = [
    "demand_volume",
    "unit_cost_usd",
    "resource_utilization_pct",
    "pipeline_throughput_recs_per_sec",
    "compute_cost_usd_per_unit"
]


# ============================================================================
# INPUT LOADING
# ============================================================================

def load_config(config_path: Path) -> dict:
    """Load simulation and scenario parameters from a JSON file."""
    if not config_path.exists():
        raise FileNotFoundError(
            f"Config file not found: {config_path}"
        )

    with open(config_path, "r", encoding="utf-8") as file:
        return json.load(file)


def load_sample_matrices(samples_file: Path) -> dict:
    """Load pre-generated sample matrices from the sensitivity analysis."""
    if not samples_file.exists():
        raise FileNotFoundError(
            f"Sample matrices not found: {samples_file}. "
            "Run 01_sensitivity_analysis_framework.py first."
        )

    with open(samples_file, "r", encoding="utf-8") as file:
        samples = json.load(file)

    print(f"✓ Loaded sample matrices from {samples_file}")

    available_structures = [
        key for key in samples.keys()
        if key in {
            "observed_gaussian",
            "independent",
            "t_copula_df5"
        }
    ]

    print(
        "  Available correlation structures: "
        f"{available_structures}"
    )

    if "variable_order" in samples:
        saved_order = samples["variable_order"]

        if saved_order != VARIABLE_ORDER:
            raise ValueError(
                "Sample-file variable order does not match the main.py "
                "expected variable order.\n"
                f"Expected: {VARIABLE_ORDER}\n"
                f"Received: {saved_order}"
            )

    return samples


# ============================================================================
# SAMPLE CONVERSION
# ============================================================================

def convert_matrix_to_scenario_samples(
    samples_matrix: np.ndarray
) -> dict:
    """
    Convert the n x 5 sensitivity-analysis matrix to the dictionary format
    expected by ScenarioA, ScenarioB, and ScenarioC.

    Matrix column order:
    0: demand_volume
    1: unit_cost_usd
    2: resource_utilization_pct
    3: pipeline_throughput_recs_per_sec
    4: compute_cost_usd_per_unit
    """
    if samples_matrix.ndim != 2 or samples_matrix.shape[1] != 5:
        raise ValueError(
            "Sample matrix must have shape (n_samples, 5). "
            f"Received: {samples_matrix.shape}"
        )

    return {
        "demand": samples_matrix[:, 0],
        "unit_cost": samples_matrix[:, 1],
        "resource_util": samples_matrix[:, 2],
        "throughput": samples_matrix[:, 3],
        "compute_cost": samples_matrix[:, 4]
    }


# ============================================================================
# SCENARIO EXECUTION
# ============================================================================

def run_scenario_on_samples(
    scenario_class,
    scenario_name: str,
    params: dict,
    samples_matrix: np.ndarray
) -> dict:
    """
    Run a single scenario on a matrix of Monte Carlo samples.

    ROI values from the scenario classes are decimal values:
    0.20 represents a 20% ROI.
    """
    try:
        scenario = scenario_class(params)

        scenario_samples = convert_matrix_to_scenario_samples(
            samples_matrix
        )

        roi_distribution = scenario.calculate_roi(scenario_samples)

        roi_threshold = params["analysis"]["threshold_exceedance_roi"]

        return {
            "scenario": scenario_name,
            "mean_roi": float(np.mean(roi_distribution)),
            "std_roi": float(np.std(roi_distribution)),
            "p5_roi": float(np.percentile(roi_distribution, 5)),
            "p95_roi": float(np.percentile(roi_distribution, 95)),
            "threshold_exceedance": float(
                np.mean(roi_distribution > roi_threshold)
            ),
            "negative_roi_probability": float(
                np.mean(roi_distribution < 0)
            ),
            "samples_count": int(len(roi_distribution))
        }

    except Exception as error:
        print(
            f"  ✗ Error running Scenario {scenario_name}: {error}"
        )
        raise


def calculate_realized_correlations(
    samples_matrix: np.ndarray
) -> dict:
    """Calculate selected realized correlations from a sample matrix."""
    demand = samples_matrix[:, 0]
    utilization = samples_matrix[:, 2]
    compute_cost = samples_matrix[:, 4]

    return {
        "demand_compute_cost": float(
            np.corrcoef(demand, compute_cost)[0, 1]
        ),
        "demand_resource_utilization": float(
            np.corrcoef(demand, utilization)[0, 1]
        )
    }


def run_all_scenarios_on_correlation_structure(
    params: dict,
    correlation_method: str,
    samples_data
) -> dict:
    """
    Run Scenarios A, B, and C using one correlation-structure sample matrix.

    Supports both a direct JSON list of sample rows and a dictionary with a
    `samples` field, although the current sensitivity script writes direct lists.
    """
    print(f"\n{'=' * 80}")
    print(f"Running scenarios on {correlation_method.upper()}")
    print(f"{'=' * 80}")

    saved_correlations = {}

    if isinstance(samples_data, list):
        samples_matrix = np.array(samples_data, dtype=float)

    elif isinstance(samples_data, dict):
        if "samples" not in samples_data:
            raise ValueError(
                f"Expected a 'samples' key for {correlation_method}; "
                f"found: {list(samples_data.keys())}"
            )

        samples_matrix = np.array(
            samples_data["samples"],
            dtype=float
        )

        saved_correlations = samples_data.get(
            "correlations",
            {}
        )

    else:
        raise TypeError(
            f"Unsupported sample format for {correlation_method}: "
            f"{type(samples_data).__name__}"
        )

    if samples_matrix.ndim != 2 or samples_matrix.shape[1] != 5:
        raise ValueError(
            f"Sample matrix for {correlation_method} must have shape "
            f"(n_samples, 5); received {samples_matrix.shape}."
        )

    if samples_matrix.shape[0] == 0:
        raise ValueError(
            f"Empty sample matrix for {correlation_method}."
        )

    print(f"Sample matrix shape: {samples_matrix.shape}")

    realized_correlations = calculate_realized_correlations(
        samples_matrix
    )

    print("Realized correlations:")

    if saved_correlations:
        for corr_name, corr_value in saved_correlations.items():
            print(f"  {corr_name}: {corr_value:.4f}")
    else:
        print(
            "  Demand–Compute Cost: "
            f"{realized_correlations['demand_compute_cost']:.4f}"
        )
        print(
            "  Demand–Resource Utilization: "
            f"{realized_correlations['demand_resource_utilization']:.4f}"
        )

    scenario_results = {}

    for scenario_class, scenario_name in [
        (ScenarioA, "A"),
        (ScenarioB, "B"),
        (ScenarioC, "C")
    ]:
        print(f"\n  Running Scenario {scenario_name}...")

        result = run_scenario_on_samples(
            scenario_class=scenario_class,
            scenario_name=scenario_name,
            params=params,
            samples_matrix=samples_matrix
        )

        scenario_results[scenario_name] = result

        print(
            f"    Mean ROI: {result['mean_roi']:.2%} | "
            f"Std: {result['std_roi']:.2%} | "
            f"P5: {result['p5_roi']:.2%} | "
            f"P95: {result['p95_roi']:.2%}"
        )

    return {
        "realized_correlations": realized_correlations,
        "scenarios": scenario_results
    }


# ============================================================================
# RANKING STABILITY
# ============================================================================

def compute_ranking_stability(
    results_by_correlation: dict
) -> dict:
    """
    Assess whether ranking by mean ROI is consistent under all
    correlation structures.
    """
    print(f"\n{'=' * 80}")
    print("RANKING STABILITY ANALYSIS")
    print(f"{'=' * 80}")

    rankings_by_structure = {}
    baseline_ranking = None
    ranking_stable = True

    for correlation_method, result_data in results_by_correlation.items():
        scenarios = result_data["scenarios"]

        ranked = sorted(
            scenarios.items(),
            key=lambda item: item[1]["mean_roi"],
            reverse=True
        )

        current_ranking = [
            scenario_name
            for scenario_name, _ in ranked
        ]

        rankings_by_structure[correlation_method] = current_ranking

        if baseline_ranking is None:
            baseline_ranking = current_ranking
        elif current_ranking != baseline_ranking:
            ranking_stable = False

        print(f"\n{correlation_method.upper()}:")
        print(f"  Ranking: {' > '.join(current_ranking)}")
        print(
            f"  Matches baseline: "
            f"{'✓ YES' if current_ranking == baseline_ranking else '✗ NO'}"
        )
        print("  Mean ROIs:")

        for scenario_name, scenario_result in ranked:
            print(
                f"    Scenario {scenario_name}: "
                f"{scenario_result['mean_roi']:.2%}"
            )

    return {
        "ranking_stable": ranking_stable,
        "baseline_method": "observed_gaussian",
        "baseline_ranking": baseline_ranking,
        "rankings_by_structure": rankings_by_structure
    }


# ============================================================================
# EXPORTS
# ============================================================================

def export_results(
    results_by_correlation: dict,
    ranking_stability: dict,
    output_file: Path,
    summary_file: Path
) -> None:
    """Export full JSON results and a readable text summary."""
    output_file.parent.mkdir(parents=True, exist_ok=True)

    export_data = {
        "results_by_correlation": results_by_correlation,
        "ranking_stability": ranking_stability,
        "metadata": {
            "timestamp": pd.Timestamp.now().isoformat(),
            "variable_order": VARIABLE_ORDER,
            "note": (
                "Sensitivity analysis comparing observed Gaussian copula, "
                "independent sampling, and t-copula with df=5."
            )
        }
    }

    with open(output_file, "w", encoding="utf-8") as file:
        json.dump(export_data, file, indent=2)

    print(f"\n✓ Full results exported to {output_file}")

    with open(summary_file, "w", encoding="utf-8") as file:
        file.write("=" * 80 + "\n")
        file.write("FINOPS MONTE CARLO RANKING STABILITY REPORT\n")
        file.write("=" * 80 + "\n\n")

        stability_label = (
            "ROBUST"
            if ranking_stability["ranking_stable"]
            else "UNSTABLE"
        )

        file.write(
            f"RANKING STABILITY: {stability_label}\n"
        )
        file.write(
            "Baseline ranking: "
            f"{' > '.join(ranking_stability['baseline_ranking'])}\n\n"
        )

        for correlation_method, result_data in results_by_correlation.items():
            scenarios = result_data["scenarios"]
            correlations = result_data["realized_correlations"]

            file.write(f"{correlation_method.upper()}:\n")
            file.write("-" * 80 + "\n")
            file.write(
                "Demand–Compute Cost Correlation: "
                f"{correlations['demand_compute_cost']:.4f}\n"
            )
            file.write(
                "Demand–Resource Utilization Correlation: "
                f"{correlations['demand_resource_utilization']:.4f}\n"
            )

            ranked = sorted(
                scenarios.items(),
                key=lambda item: item[1]["mean_roi"],
                reverse=True
            )

            for rank, (scenario_name, result) in enumerate(ranked, start=1):
                file.write(f"\n{rank}. Scenario {scenario_name}\n")
                file.write(
                    f"   Mean ROI:                  "
                    f"{result['mean_roi']:>12.2%}\n"
                )
                file.write(
                    f"   Std Dev:                   "
                    f"{result['std_roi']:>12.2%}\n"
                )
                file.write(
                    f"   P5 (pessimistic):          "
                    f"{result['p5_roi']:>12.2%}\n"
                )
                file.write(
                    f"   P95 (optimistic):          "
                    f"{result['p95_roi']:>12.2%}\n"
                )
                file.write(
                    f"   Threshold Exceedance:      "
                    f"{result['threshold_exceedance']:>12.2%}\n"
                )
                file.write(
                    f"   Negative ROI Probability:  "
                    f"{result['negative_roi_probability']:>12.2%}\n"
                )

            file.write("\n\n")

    print(f"✓ Summary exported to {summary_file}")


# ============================================================================
# MAIN
# ============================================================================

def main():
    """Run ranking-stability analysis across all saved sample matrices."""
    print("\n" + "=" * 80)
    print("FINOPS MONTE CARLO FRAMEWORK - RANKING STABILITY ANALYSIS")
    print("=" * 80)

    print("\n[1/5] Loading configuration...")
    params = load_config(CONFIG_PATH)
    print(f"✓ Configuration loaded from {CONFIG_PATH}")

    print("\n[2/5] Loading sample matrices from sensitivity analysis...")
    samples_by_correlation = load_sample_matrices(SAMPLES_FILE)

    print("\n[3/5] Running scenarios on each correlation structure...")

    correlation_methods = [
        "observed_gaussian",
        "independent",
        "t_copula_df5"
    ]

    results_by_correlation = {}

    for correlation_method in correlation_methods:
        if correlation_method not in samples_by_correlation:
            print(
                f"  ✗ Warning: {correlation_method} was not found "
                "in the samples file."
            )
            continue

        results_by_correlation[correlation_method] = (
            run_all_scenarios_on_correlation_structure(
                params=params,
                correlation_method=correlation_method,
                samples_data=samples_by_correlation[correlation_method]
            )
        )

    if not results_by_correlation:
        raise RuntimeError(
            "No valid correlation-structure sample matrices were found."
        )

    print("\n[4/5] Analyzing ranking stability...")
    ranking_stability = compute_ranking_stability(
        results_by_correlation
    )

    print("\n[5/5] Exporting results...")
    export_results(
        results_by_correlation=results_by_correlation,
        ranking_stability=ranking_stability,
        output_file=RANKING_OUTPUT,
        summary_file=RANKING_SUMMARY
    )

    print("\n" + "=" * 80)
    print("✓ RANKING STABILITY ANALYSIS COMPLETE")
    print("=" * 80)

    print("\nKey Findings:")
    print(
        f"  Ranking stable: "
        f"{ranking_stability['ranking_stable']}"
    )
    print(
        "  Baseline ranking: "
        f"{' > '.join(ranking_stability['baseline_ranking'])}"
    )

    print("\nOutputs:")
    print(f"  - Full results: {RANKING_OUTPUT}")
    print(f"  - Summary: {RANKING_SUMMARY}")

    return results_by_correlation, ranking_stability


if __name__ == "__main__":
    main()